version: "3"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=myusername
      - POSTGRES_PASSWORD=mypassword
    ports:
      - '5432:5432'
    volumes: 
      - db-data:/var/lib/postgresql/data
    networks:
      - hub-app
  react-app:
    build:
      dockerfile: Dockerfile
      context: ./client
    stdin_open: true
    ports: 
      - "3001:3000"
    networks:
      - hub-app
    depends_on:
        - api-server
  api-server:
    build:
      dockerfile: Dockerfile
      context: ./server
    image: api-server
    ports:
      - "8081:8080"
    networks:
      - hub-app
    depends_on:
      - db
networks:
  hub-app:
    driver: bridge

volumes:
  db-data:
    driver: local